imports:
    - { resource: resources.yaml }
    - { resource: sylius_ui.yaml }
    - { resource: grids.yaml }


knp_gaufrette:
    stream_wrapper: ~
    adapters:
        social_media_logo:
            local:
                directory: "%sylius_core.public_dir%/media/social-media-logo"
                create: true
    filesystems:
        social_media_logo:
            adapter: social_media_logo

liip_imagine:
    loaders:
        social_media_logo:
            filesystem:
                data_root: "%kernel.project_dir%/public/media/social-media-logo"
    filter_sets:
        dotit_sylius_appearance_plugin_logo:
            data_loader: social_media_logo
            filters:
                thumbnail: { size: [300, 300], mode: outbound }
