Dotit\SyliusAppearancePlugin\Entity\SocialMedia:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name]
            message: 'dotit_sylius_appearance_plugin.social_media.name.unique'
            groups: ['dotit_logo_create']
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [slug]
            message: 'dotit_sylius_appearance_plugin.social_media.slug.unique'
            groups: ['dotit_logo_create']

    properties:
        name:
            - NotBlank:
                message: 'dotit_sylius_appearance_plugin.social_media.name.not_blank'
                groups: ['dotit_logo_create']
            - Length:
                min: 2
                max: 250
                minMessage: 'dotit_sylius_appearance_plugin.social_media.name.min_length'
                maxMessage: 'dotit_sylius_appearance_plugin.social_media.name.max_length'
                groups: ['dotit_logo_create']
        url:
          - NotBlank:
              message: 'dotit_sylius_appearance_plugin.social_media.url.not_blank'
              groups: [ 'dotit_logo_create' ]
          - Length:
              min: 2
              max: 250
              minMessage: 'dotit_sylius_appearance_plugin.social_media.url.min_length'
              maxMessage: 'dotit_sylius_appearance_plugin.social_media.url.max_length'
              groups: [ 'dotit_logo_create' ]

        slug:
            - NotBlank:
                message: 'dotit_sylius_appearance_plugin.social_media.slug.not_blank'
                groups: ['dotit_logo_create']
            - Length:
                min: 2
                max: 250
                minMessage: 'dotit_sylius_appearance_plugin.social_media.slug.min_length'
                maxMessage: 'dotit_sylius_appearance_plugin.social_media.slug.max_length'
                groups: ['dotit_logo_create']

        logoFile:
            - NotBlank:
                message: 'dotit_sylius_appearance_plugin.social_media.logo_file.not_blank'
                groups: ['dotit_logo_create']


