dotit_sylius_appearance_plugin_admin_social_media:
  resource: |
    alias: dotit_sylius_appearance_plugin.social_media
    section: admin
    templates: "@SyliusAdmin/Crud"
    except: ['show']
    redirect: index
    grid: dotit_sylius_appearance_plugin_admin_social_media
    permission: true
    vars:
        all:
            subheader: dotit_sylius_appearance_plugin.ui.manage_stores
            templates:
                form: '@DotitSyliusAppearancePlugin/Admin/social_media/_form.html.twig'
        index:
            icon: trademark
  type: sylius.resource

