dotit_sylius_appearance_plugin_admin_ajax_social_media_generate_slug:
  path: /generate-slug
  methods: [GET]
  defaults:
    _controller: dotit_sylius_appearance_plugin.controller.social_media_slug::generate
    _format: json
